name: "Bug report"
description: Create a bug report
title: "[BUG] - "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Describe the issue
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Reproduction steps"
      description: Describe the protocol to reproduce this issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: text
    validations:
      required: false
